version: "3.9"

services:
  db:
    image: postgres:15
    container_name: storerating_db
    restart: always
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: store_rating_db
    ports:
      - "5432:5432"
    volumes:
      - ./models/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: storerating_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
